name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      browser:
        description: 'Browser to run tests in'
        required: true
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox
        - webkit
        - all

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.5.3

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright Browsers
      run: |
        dotnet build
        playwright install

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: |
        dotnet test --configuration Release --logger "console;verbosity=detailed" --logger "trx;LogFileName=TestResults.trx"

    - name: Check if test results exist
      id: check_results
      run: |
        if (Test-Path "TestResults/TestResults.trx") {
          echo "exists=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "exists=false" >> $env:GITHUB_OUTPUT
        }

    - name: Install ReportGenerator
      if: steps.check_results.outputs.exists == 'true'
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      if: steps.check_results.outputs.exists == 'true'
      run: |
        reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"CoverageReport" -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

    - name: Upload Test Results
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: test-results
        path: TestResults

    - name: Upload Coverage Report
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: coverage-report
        path: CoverageReport

    - name: Upload Screenshots
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: screenshots
        path: screenshots

    - name: Upload Videos
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: videos
        path: videos

    - name: Upload Logs
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: logs
        path: logs 